/**
 * Sharing Utilities
 * Handles sharing presentations via various channels
 */

/**
 * Generate shareable link for presentation
 * @param {Object} report - Report object with presentation
 * @returns {string} - Shareable URL
 */
export function generateShareLink(report) {
  const baseUrl = typeof window !== 'undefined' ? window.location.origin : '';
  const basePath = '/Ward-rounds'; // GitHub Pages base path
  const reportId = report.id || Date.now().toString();

  // Store report in localStorage for sharing
  if (typeof window !== 'undefined') {
    const shareKey = `shared_report_${reportId}`;
    localStorage.setItem(shareKey, JSON.stringify({
      report,
      sharedAt: new Date().toISOString(),
      expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString() // 7 days
    }));
  }

  return `${baseUrl}${basePath}/shared/?id=${reportId}`;
}

/**
 * Copy link to clipboard
 * @param {string} link - Link to copy
 * @returns {Promise<boolean>} - Success status
 */
export async function copyToClipboard(link) {
  try {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      await navigator.clipboard.writeText(link);
      return true;
    } else {
      // Fallback for older browsers
      const textArea = document.createElement('textarea');
      textArea.value = link;
      textArea.style.position = 'fixed';
      textArea.style.left = '-999999px';
      document.body.appendChild(textArea);
      textArea.focus();
      textArea.select();

      const success = document.execCommand('copy');
      document.body.removeChild(textArea);
      return success;
    }
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
}

/**
 * Share via Web Share API (mobile)
 * @param {Object} data - Share data
 * @returns {Promise<boolean>} - Success status
 */
export async function shareViaWebShare(data) {
  if (!navigator.share) {
    return false;
  }

  try {
    await navigator.share({
      title: data.title || 'Ward Presentation',
      text: data.text || 'Check out this medical presentation',
      url: data.url
    });
    return true;
  } catch (error) {
    if (error.name !== 'AbortError') {
      console.error('Share failed:', error);
    }
    return false;
  }
}

/**
 * Share via Email
 * @param {Object} presentation - Presentation data
 * @param {string} shareLink - Shareable link
 */
export function shareViaEmail(presentation, shareLink) {
  const subject = encodeURIComponent('Ward Presentation');
  const body = encodeURIComponent(
    `I'd like to share this ward presentation with you:\n\n` +
    `${presentation.oneLiner || 'Medical presentation'}\n\n` +
    `View online: ${shareLink}\n\n` +
    `Generated by MedWard`
  );

  window.location.href = `mailto:?subject=${subject}&body=${body}`;
}

/**
 * Share via WhatsApp
 * @param {Object} presentation - Presentation data
 * @param {string} shareLink - Shareable link
 */
export function shareViaWhatsApp(presentation, shareLink) {
  const text = encodeURIComponent(
    `*Ward Presentation*\n\n` +
    `${presentation.oneLiner || 'Medical presentation'}\n\n` +
    `View: ${shareLink}`
  );

  // Mobile WhatsApp
  if (/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)) {
    window.location.href = `whatsapp://send?text=${text}`;
  } else {
    // WhatsApp Web
    window.open(`https://web.whatsapp.com/send?text=${text}`, '_blank');
  }
}

/**
 * Share via Telegram
 * @param {Object} presentation - Presentation data
 * @param {string} shareLink - Shareable link
 */
export function shareViaTelegram(presentation, shareLink) {
  const text = encodeURIComponent(
    `Ward Presentation\n\n${presentation.oneLiner || ''}\n\n${shareLink}`
  );

  window.open(`https://t.me/share/url?url=${shareLink}&text=${text}`, '_blank');
}

/**
 * Share via Twitter/X
 * @param {Object} presentation - Presentation data
 * @param {string} shareLink - Shareable link
 */
export function shareViaTwitter(presentation, shareLink) {
  const text = encodeURIComponent(
    `Ward Presentation: ${presentation.oneLiner || 'Medical case presentation'}`
  );

  window.open(
    `https://twitter.com/intent/tweet?text=${text}&url=${shareLink}`,
    '_blank'
  );
}

/**
 * Generate QR code for sharing
 * @param {string} link - Link to encode
 * @returns {string} - QR code data URL
 */
export function generateQRCode(link) {
  // Using Google Charts API for simple QR code generation
  const size = 300;
  const encodedLink = encodeURIComponent(link);
  return `https://chart.googleapis.com/chart?cht=qr&chs=${size}x${size}&chl=${encodedLink}`;
}

/**
 * Download presentation as JSON
 * @param {Object} presentation - Presentation data
 * @param {string} fileName - File name
 */
export function downloadAsJSON(presentation, fileName = 'presentation.json') {
  const dataStr = JSON.stringify(presentation, null, 2);
  const dataBlob = new Blob([dataStr], { type: 'application/json' });
  const url = URL.createObjectURL(dataBlob);

  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Print presentation
 */
export function printPresentation() {
  window.print();
}

/**
 * Check if Web Share API is available
 * @returns {boolean}
 */
export function isWebShareAvailable() {
  return typeof navigator !== 'undefined' && 'share' in navigator;
}

/**
 * Check if device is mobile
 * @returns {boolean}
 */
export function isMobileDevice() {
  if (typeof window === 'undefined') return false;
  return /Android|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
}

/**
 * Get available share methods
 * @returns {Array<Object>} - Available share methods with metadata
 */
export function getAvailableShareMethods() {
  const methods = [
    {
      id: 'link',
      name: 'Copy Link',
      icon: '🔗',
      description: 'Copy shareable link to clipboard',
      available: true
    },
    {
      id: 'email',
      name: 'Email',
      icon: '📧',
      description: 'Share via email',
      available: true
    },
    {
      id: 'whatsapp',
      name: 'WhatsApp',
      icon: '💬',
      description: 'Share via WhatsApp',
      available: true
    },
    {
      id: 'telegram',
      name: 'Telegram',
      icon: '✈️',
      description: 'Share via Telegram',
      available: true
    },
    {
      id: 'qr',
      name: 'QR Code',
      icon: '📱',
      description: 'Generate QR code for easy scanning',
      available: true
    },
    {
      id: 'native',
      name: 'Share',
      icon: '📤',
      description: 'Use device share menu',
      available: isWebShareAvailable()
    }
  ];

  return methods.filter(m => m.available);
}
