'use client';

import { useEffect, useState, Suspense } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import { PresentationView } from '@/components/presentation/PresentationView';

/**
 * Inner component that uses useSearchParams
 * Wrapped in Suspense to avoid SSR issues
 */
function SharedPresentationContent() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const [presentation, setPresentation] = useState(null);
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const reportId = searchParams.get('id');
    if (!reportId) {
      setError('Invalid share link');
      setLoading(false);
      return;
    }

    // Load shared report from localStorage
    const shareKey = `shared_report_${reportId}`;
    const sharedData = localStorage.getItem(shareKey);

    if (!sharedData) {
      setError('Presentation not found or expired');
      setLoading(false);
      return;
    }

    try {
      const data = JSON.parse(sharedData);

      // Check if expired
      if (data.expiresAt && new Date(data.expiresAt) < new Date()) {
        localStorage.removeItem(shareKey);
        setError('This presentation has expired');
        setLoading(false);
        return;
      }

      setReport(data.report);
      setPresentation(data.report.presentation || {});
      setLoading(false);
    } catch (err) {
      console.error('Error loading shared presentation:', err);
      setError('Failed to load presentation');
      setLoading(false);
    }
  }, [searchParams]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-slate-50 dark:bg-slate-900">
        <div className="text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-4 border-primary border-t-transparent mx-auto mb-4"></div>
          <p className="text-slate-600 dark:text-slate-400">Loading presentation...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-slate-50 dark:bg-slate-900">
        <div className="text-center max-w-md mx-4">
          <div className="text-6xl mb-4">⚠️</div>
          <h1 className="text-2xl font-bold text-slate-900 dark:text-white mb-2">
            {error}
          </h1>
          <p className="text-slate-600 dark:text-slate-400 mb-6">
            {error.includes('expired')
              ? 'Shared presentations expire after 7 days for privacy.'
              : 'Please check the link and try again.'}
          </p>
          <button
            onClick={() => router.push('/login')}
            className="px-6 py-3 bg-primary text-white rounded-xl font-medium hover:bg-primary-dark transition-colors"
          >
            Go to Login
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-900">
      {/* Header */}
      <div className="bg-white dark:bg-slate-800 border-b border-slate-200 dark:border-slate-700 sticky top-0 z-20">
        <div className="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between">
          <div>
            <h1 className="text-xl font-bold text-slate-900 dark:text-white">
              Shared Presentation
            </h1>
            <p className="text-sm text-slate-600 dark:text-slate-400">
              Generated by MedWard
            </p>
          </div>
          <button
            onClick={() => router.push('/login')}
            className="px-4 py-2 bg-primary text-white rounded-lg font-medium hover:bg-primary-dark transition-colors text-sm"
          >
            Try MedWard
          </button>
        </div>
      </div>

      {/* Presentation */}
      <div className="max-w-4xl mx-auto p-4 h-[calc(100vh-80px)]">
        <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-card overflow-hidden h-full">
          <PresentationView
            presentation={presentation}
            pearls={report?.clinicalPearls?.pearls || []}
            questions={report?.potentialQuestions?.questions || []}
            report={report}
          />
        </div>
      </div>

      {/* Footer */}
      <div className="fixed bottom-0 left-0 right-0 bg-white/80 dark:bg-slate-800/80 backdrop-blur-sm border-t border-slate-200 dark:border-slate-700 py-3">
        <div className="max-w-7xl mx-auto px-4 text-center">
          <p className="text-sm text-slate-600 dark:text-slate-400">
            Created with{' '}
            <a
              href="/"
              className="text-primary hover:underline font-medium"
            >
              MedWard
            </a>
            {' '}• Medical Report Interpretation System
          </p>
        </div>
      </div>
    </div>
  );
}

/**
 * Shared Presentation Page
 * Displays publicly shared presentations using query parameter
 * Usage: /shared?id=[reportId]
 */
export default function SharedPresentationPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen flex items-center justify-center bg-slate-50 dark:bg-slate-900">
        <div className="text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-4 border-primary border-t-transparent mx-auto mb-4"></div>
          <p className="text-slate-600 dark:text-slate-400">Loading presentation...</p>
        </div>
      </div>
    }>
      <SharedPresentationContent />
    </Suspense>
  );
}
